---
kind: pipeline
name: default

steps:

  - name: set permissions
    image: alpine:edge
    commands:
      - chown -Rv 1000:1000 .

  - name: py36
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e py36

  - name: py37
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e py37

  - name: flake8
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e flake8

  - name: pylint
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e pylint

  - name: mypy
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e mypy

  - name: black
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e black-only-check

  - name: shiv
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - mkdir dist/
      - tox -v -e shiv-py36
      - tox -v -e shiv-py37

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
